package scorex.block

import com.google.common.primitives.{Ints, Longs}
import play.api.libs.json.Json
import scorex.consensus.{BasicConsensusBlockData, ConsensusModule}
import scorex.crypto.encode.Base58
import scorex.serialization.BytesSerializable
import scorex.transaction.{Transaction, TransactionModule}
import scorex.utils.ScorexLogging

import scala.util.{Failure, Try}

/**
  * A block is an atomic piece of data network participates are agreed on.
  *
  * A block has:
  * - transactions data: a sequence of transactions, where a transaction is an atomic state update.
  * Some metadata is possible as well(transactions Merkle tree root, state Merkle tree root etc).
  *
  * - consensus data to check whether block was generated by a right party in a right way. E.g.
  * "baseTarget" & "generatorSignature" fields in the Nxt block structure, nonce & difficulty in the
  * Bitcoin block structure.
  *
  * - a signature(s) of a block generator(s)
  *
  * - additional data: block structure version no, timestamp etc
  */

trait Block[TX <: Transaction] extends BytesSerializable with ScorexLogging {
  type ConsensusDataType <: BasicConsensusBlockData
  type TransactionDataType

  implicit val consensusModule: ConsensusModule[ConsensusDataType, TX]
  implicit val transactionModule: TransactionModule[TransactionDataType, TX]

  val consensusDataField: BlockField[ConsensusDataType]
  val transactionDataField: BlockField[TransactionDataType]

  val versionField: ByteBlockField
  val timestampField: LongBlockField

  lazy val id = consensusModule.id(this)

  lazy val parentId = consensusModule.parentId(this)

  lazy val encodedId: String = Base58.encode(consensusModule.id(this))

  lazy val transactions: Seq[TX] = transactionModule.transactions(this)

  lazy val totalFee = consensusModule.feesDistribution(this).values.sum

  lazy val json =
    versionField.json ++
      timestampField.json ++
      consensusDataField.json ++
      transactionDataField.json ++
      Json.obj(
        "fee" -> totalFee,
        "blocksize" -> bytes.length
      )

  lazy val bytes = {
    val txBytesSize = transactionDataField.bytes.length
    val txBytes = Ints.toByteArray(txBytesSize) ++ transactionDataField.bytes

    val cBytesSize = consensusDataField.bytes.length
    val cBytes = Ints.toByteArray(cBytesSize) ++ consensusDataField.bytes

    versionField.bytes ++
      timestampField.bytes ++
      cBytes ++
      txBytes
  }

  lazy val producers = consensusModule.producers(this)

  def isValid: Boolean = {
    if (transactionModule.blockStorage.history.contains(this)) true //applied blocks are valid
    else {
      lazy val consensus = consensusModule.isValid(this)
      lazy val transaction = transactionModule.isValid(this)

      if (!consensus) log.debug(s"Invalid block $encodedId: consensus data is not valid")
      else if (!transaction) log.debug(s"Invalid block $encodedId: transaction data is not valid")

      consensus && transaction
    }
  }

  override def equals(obj: Any): Boolean = obj match {
    case b: Block[TX] => consensusModule.id(b) sameElements consensusModule.id(this)
    case _ => false
  }
}


object Block extends ScorexLogging {
  type BlockId = Array[Byte]

  //TODO BytesParseable[Block] ??
  def parseBytes[CDT  <: BasicConsensusBlockData, TDT, TX <: Transaction](bytes: Array[Byte])
                                             (implicit consModule: ConsensusModule[CDT, TX],
                                              transModule: TransactionModule[TDT, TX]): Try[Block[TX]] = Try {

    val version = bytes.head

    var position = 1

    val timestamp = Longs.fromByteArray(bytes.slice(position, position + 8))
    position += 8

    val cBytesLength = Ints.fromByteArray(bytes.slice(position, position + 4))
    position += 4
    val cBytes = bytes.slice(position, position + cBytesLength)
    val consBlockField = consModule.parseBytes(cBytes).get
    position += cBytesLength

    val tBytesLength = Ints.fromByteArray(bytes.slice(position, position + 4))
    position += 4
    val tBytes = bytes.slice(position, position + tBytesLength)
    val txBlockField = transModule.parseBytes(tBytes).get
    position += tBytesLength

    new Block[TX] {

      override type ConsensusDataType = CDT
      override type TransactionDataType = TDT

      override val transactionDataField: BlockField[TransactionDataType] = txBlockField

      override implicit val consensusModule: ConsensusModule[ConsensusDataType, TX] = consModule
      override implicit val transactionModule: TransactionModule[TransactionDataType, TX] = transModule

      override val versionField: ByteBlockField = ByteBlockField("version", version)

      override val consensusDataField: BlockField[ConsensusDataType] = consBlockField

      override val timestampField: LongBlockField = LongBlockField("timestamp", timestamp)
    }
  }.recoverWith { case t: Throwable =>
    log.error("Error when parsing block", t)
    t.printStackTrace()
    Failure(t)
  }

  def build[CDT <: BasicConsensusBlockData, TT, TDT, TX <: Transaction](version: Byte,
                                             timestamp: Long,
                                             consensusData: CDT,
                                             transactionData: TDT)
                                            (implicit consModule: ConsensusModule[CDT, TX],
                                             transModule: TransactionModule[TDT, TX]): Block[TX] = {
    new Block[TX] {
      override type ConsensusDataType = CDT
      override type TransactionDataType = TDT

      override implicit val transactionModule: TransactionModule[TDT, TX] = transModule
      override implicit val consensusModule: ConsensusModule[CDT, TX] = consModule

      override val versionField: ByteBlockField = ByteBlockField("version", version)

      override val transactionDataField: BlockField[TDT] = transModule.formBlockData(transactionData)

      override val consensusDataField: BlockField[CDT] = consensusModule.formBlockData(consensusData)
      override val timestampField: LongBlockField = LongBlockField("timestamp", timestamp)
    }
  }

  def genesis[CDT <: BasicConsensusBlockData, TDT, TX <: Transaction](timestamp: Long = 0L)(implicit consModule: ConsensusModule[CDT, TX],
                                                                 transModule: TransactionModule[TDT, TX]): Block[TX] = new Block[TX] {
    override type ConsensusDataType = CDT
    override type TransactionDataType = TDT

    override implicit val transactionModule: TransactionModule[TDT, TX] = transModule
    override implicit val consensusModule: ConsensusModule[CDT, TX] = consModule

    override val versionField: ByteBlockField = ByteBlockField("version", 1)
    override val transactionDataField: BlockField[TDT] = transactionModule.genesisData
    override val consensusDataField: BlockField[CDT] = consensusModule.genesisData

    override val timestampField: LongBlockField = LongBlockField("timestamp", timestamp)
  }
}